oldest:
  cli: "experiment.oldest"
  singularity: "mrs"
  architecture: "leader_follower"
  similarity: "homogeneous"
  sensors:
    odom_gps:
      ros:
        msg_type: "nav_msgs/Odometry"
        name: "odometry/odom_gps"
    rp_a2:
      ros:
        msg_type: "sensor_msgs/LaserScan"
        name: "rplidar/scan"
  robots:
    model: "tarot_t650"
    mind:
      learn: null
      memory:
        remembering: null
    members:
      leader:
        id: "uav1"
        ros:
          name: "uav1"
      follower:
        id: "uav2"
        ros:
          name: "uav2"
  learning_scenrios: [normal]
  testing_scenrios: [follow, next_to]
